default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_ror_development

test:
  <<: *default
  database: blog_ror_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: blog_ror_production
  username: blog_ror
  password: <%= ENV['BLOG_ROR_DATABASE_PASSWORD'] %>
